accent = "#4A4E3D"
cursor = "#FF4500"
foreground = "#E0D4C2"
background = "#0F0F0F"
selection_foreground = "#E24C00"
selection_background = "#3A403B"

color0 = "#0F0F0F"
color1 = "#8B0000"
color2 = "#3A403B"
color3 = "#FF4500"
color4 = "#4A4E3D"
color5 = "#7B726A"
color6 = "#7A7D80"
color7 = "#bebebe"
color8 = "#292828"
color9 = "#8B0000"
color10 = "#305432"
color11 = "#FF4500"
color12 = "#496529"
color13 = "#7B726A"
color14 = "#7A7D80"
color15 = "#bebebe"
